### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Nurgak** [arduino/compile-sketches#86]
### Describe the problem

When using the action the following warning appears:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

There are [some mentions of `set-output`](https://github.com/arduino/compile-sketches/search?q=set-output&type=code) in this action that should probably be taken care of.

### To reproduce

Use the action, check the output warnings.

### Expected behavior

No warnings appear during action execution.

### 'arduino/compile-sketches' version

1.0.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/compile-sketches/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by MathewHDYT** [comment]
@per1234 Would be nice if this could be merged, if this isn't done than according to this [blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) by GitHub actions using the `set-output` or `set-state`, will simply fail starting 1st June 2023.
